version: "3.7"

services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"

  audiolizer:
    image: apembroke/audiolizer:0.4.11
    build: .
    ports:
      - "8000:5000"
    environment:
      AUDIOLIZER_TEMP: /home/audiolizer/audiolizer/history
    command: ["gunicorn", "--workers=4", "--bind", "0.0.0.0:5000", "audiolizer:server"]
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/audiolizer
    working_dir: /home/audiolizer/audiolizer

  audiolizer-dev:
    image: apembroke/audiolizer:latest
    ports:
      - "80:8050"
      - "8888:8888"
    environment:
      AUDIOLIZER_TEMP: /home/audiolizer/audiolizer/history
    command: ["python", "audiolizer.py"] # runs on port 8051
    # command: ["jupyter", "notebook", "audiolizer.py", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/audiolizer
    working_dir: /home/audiolizer/audiolizer
