
version: "3.2"

services:
  audiolizer:
    image: apembroke/audiolizer
    ports:
      - "8051:8051"
    environment:
      AUDIOLIZER_TEMP: /home/audiolizer/audiolizer/history
    command: ["python", "audiolizer.py"]
    volumes:
      - type: bind
        source: ${AUDIOLIZER_ASSETS}
        target: /home/audiolizer/audiolizer/assets
      - type: bind
        source: ${AUDIOLIZER_PRICES}
        target: /home/audiolizer/audiolizer/history
  audiolizer-dev:
    image: apembroke/audiolizer
    ports:
      - "8051:8051"
      - "8888:8888"
    environment:
      AUDIOLIZER_TEMP: /home/audiolizer/audiolizer/history
    command: ["jupyter", "notebook", "audiolizer.py", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
    volumes:
      - type: bind
        source: ${AUDIOLIZER_ASSETS}
        target: /home/audiolizer/audiolizer/assets
      - type: bind
        source: ${AUDIOLIZER_PRICES}
        target: /home/audiolizer/audiolizer/history
      - type: bind
        source: ${AUDIOLIZER_SRC}
        target: /home/audiolizer

        