site_name: Market Audiolizer

site_url: https://audible-markets.com/

repo_url: https://github.com/Audiolizer/audiolizer

nav:
- Home: README.md
- How it works: About.md
- WorkLog: WorkLog.md

theme:
  name: material
  logo: assets/audiolizer_icon.jpg

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences

  # - mdx_math:
  #     enable_dollar_delimiter: True 
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
