# This is a basic workflow to help you get started with Actions

name: automate.yml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - '.github/workflows/automate.yml'
    schedule:
      - cron: "*/5 * * * *"

    branches:       #[ master ]
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-workspace:
    name: github-workspace
    runs-on: ubuntu-18.04
    steps:
      - name: Print github workspace
        run: |
          printenv

  docker-ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Make
        run: |
          AUDIOLIZER_ASSETS=~/audio_files
          AUDIOLIZER_PRICES=~/price_data
          AUDIOLIZER_SRC=~/audiolizer
          JUPYTER_PASSWORD=changeme
          export AUDIOLIZER_ASSETS
          export AUDIOLIZER_PRICES
          export AUDIOLIZER_SRC
          export JUPYTER_PASSWORD
          sudo docker-compose up audiolizer
          #docker run -v /tmp/audio_files:/home/audiolizer/audiolizer/assets -v /tmp/price_data:/home/audiolizer/audiolizer/history -p 8051:8051 -it apembroke/audiolizer

  docker-macos-10-15:
    runs-on: macos-10.15
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Make
        run: |
          brew install docker-compose
          docker run -v /tmp/audio_files:/home/audiolizer/audiolizer/assets -v /tmp/price_data:/home/audiolizer/audiolizer/history -p 8051:8051 -it apembroke/audiolizer

  ubuntu-18-self-host:
    runs-on: self-hosted
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: docker-run
        run: |
          sudo docker run -v /tmp/audio_files:/home/audiolizer/audiolizer/assets -v /tmp/price_data:/home/audiolizer/audiolizer/history -p 8051:8051 -it apembroke/audiolizer

  ubuntu-18-self-host2:
    runs-on: self-hosted
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Make
        run: |
          #docker-compose up audiolizer
          AUDIOLIZER_ASSETS=~/audio_files
          AUDIOLIZER_PRICES=~/price_data
          AUDIOLIZER_SRC=~/audiolizer
          JUPYTER_PASSWORD=changeme
          PUBLIC_PORT=80
          export AUDIOLIZER_ASSETS
          export AUDIOLIZER_PRICES
          export AUDIOLIZER_SRC
          export JUPYTER_PASSWORD
          export PUBLIC_PORT
          sudo docker run -v $(AUDIOLIZER_ASSETS):/home/audiolizer/audiolizer/assets -v $(AUDIOLIZER_PRICES):/home/audiolizer/audiolizer/history -p $(PUBLIC_PORT):8051 -it apembroke/audiolizer

